# Build if_conditional program

objects = if_conditional.o
ASFLAGS = --gstabs
AS = as
CC = gcc

if_conditional: $(objects)

.PHONY: clean allclean
clean:
	rm -f $(objects)
allclean: clean
	rm if_conditional
