# Build coin_flips2a program

objects = coin_flips2a.o
ASFLAGS = --gstabs
AS = as
CC = gcc

coin_flips2a: $(objects)

.PHONY: clean allclean
clean:
	rm -f $(objects)
allclean: clean
	rm coin_flips2a

