# Build if_else_ladder program

objects = if_else_ladder.o
ASFLAGS = --gstabs
AS = as
CC = gcc

if_else_ladder: $(objects)

.PHONY: clean allclean
clean:
	rm -f $(objects)
allclean: clean
	rm if_else_ladder
