# Build if__else_ladder program

objects = if__else_ladder.o
ASFLAGS = --gstabs
AS = as
CC = gcc

if__else_ladder: $(objects)

.PHONY: clean allclean
clean:
	rm -f $(objects)
allclean: clean
	rm if__else_ladder
